name: Documentation CI
on:
  push:
    paths:
      - 'docs/**'
      - 'adrs/**'
      - '**.md'
      - '!README.md'
jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown Lint
        uses: avto-dev/markdown-lint@v1
      - name: ADR Coverage
        run: |
          test -d adrs && [ $(ls adrs | wc -l) -gt 0 ] || (echo "No ADRs found!" && exit 1)
